# Generated by Django 5.2.17 on 2026-10-03 06:19

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="Complainant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=20)),
                ("address", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ref_no", models.CharField(max_length=32)),
                (
                    "source_platform",
                    models.CharField(
                        choices=[
                            ("cm_window", "CM Window"),
                            ("jan_samvad", "Jan Samvad"),
                            ("samadhan_shivir", "Samadhan Shivir"),
                            ("social_media", "Social Media"),
                            ("internal", "Internal"),
                        ],
                        max_length=30,
                    ),
                ),
                ("external_ref", models.CharField(blank=True, max_length=100)),
                ("received_on", models.DateField()),
                ("subject", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("AWAITING_REPORT", "Awaiting report"),
                            ("UNDER_REVIEW", "Under review"),
                            ("APPROVED", "Approved"),
                            ("PORTAL_SUBMITTED", "Portal submitted"),
                            ("CLOSED", "Closed"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("current_stage_started_at", models.DateTimeField()),
                ("closed_on", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-received_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("complaint", "Complaint"),
                            ("notice", "Notice"),
                            ("inquiry_report", "Inquiry report"),
                            ("atr", "ATR"),
                            ("portal_ack", "Portal acknowledgement"),
                            ("portal_rejection", "Portal rejection"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(max_length=255, upload_to="documents/")),
                ("sha256", models.CharField(max_length=64)),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("extracted_text", models.TextField(blank=True)),
                (
                    "text_status",
                    models.CharField(
                        choices=[
                            ("none", "Not extracted"),
                            ("done", "Extracted"),
                            ("failed", "Failed"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["uploaded_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("COMPLAINT_REGISTERED", "Complaint Registered"),
                            ("NOTICE_ISSUED", "Notice Issued"),
                            ("REPORT_RECEIVED", "Report Received"),
                            ("REVIEW_SATISFIED", "Review Satisfied"),
                            ("REVIEW_NOT_SATISFIED", "Review Not Satisfied"),
                            ("PORTAL_SUBMITTED", "Portal Submitted"),
                            ("PORTAL_ACCEPTED", "Portal Accepted"),
                            ("PORTAL_REJECTED", "Portal Rejected"),
                            ("CLOSED", "Closed"),
                            ("REOPENED", "Reopened"),
                            ("DOCUMENT_ATTACHED", "Document Attached"),
                            ("DETAILS_EDITED", "Details Edited"),
                            ("NOTE_ADDED", "Note Added"),
                        ],
                        max_length=30,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="InquiryReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("received_on", models.DateField()),
                (
                    "review_outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("satisfied", "Satisfied"),
                            ("not_satisfied", "Not satisfied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_note", models.TextField(blank=True)),
                ("reviewed_on", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PortalSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_no", models.PositiveSmallIntegerField()),
                ("submitted_on", models.DateField()),
                ("portal_ack_no", models.CharField(blank=True, max_length=100)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("outcome_on", models.DateField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["complaint_id", "attempt_no"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("round_no", models.PositiveSmallIntegerField()),
                ("issued_on", models.DateField()),
                ("due_on", models.DateField()),
                ("closed_on", models.DateField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("report_received", "Report received"),
                            ("no_response", "No response"),
                            ("superseded", "Superseded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["complaint_id", "round_no"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
