# Generated by Django 5.2.17 on 2026-10-03 06:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("complaints", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complainant",
            name="office",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.office"),
        ),
        migrations.AddField(
            model_name="complainant",
            name="village",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.village",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.category",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="complainant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="complaints",
                to="complaints.complainant",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="current_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="office",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.office"),
        ),
        migrations.AddField(
            model_name="complaint",
            name="related_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="related_complaints",
                to="complaints.complaint",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="village",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.village",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="complaint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="complaints.complaint",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="office",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.office"),
        ),
        migrations.AddField(
            model_name="document",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="superseded_by",
                to="complaints.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="complaint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="complaints.complaint",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="office",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.office"),
        ),
        migrations.AddField(
            model_name="inquiryreport",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="complaints.document",
            ),
        ),
        migrations.AddField(
            model_name="inquiryreport",
            name="office",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.office"),
        ),
        migrations.AddField(
            model_name="inquiryreport",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="portalsubmission",
            name="complaint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="complaints.complaint",
            ),
        ),
        migrations.AddField(
            model_name="portalsubmission",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="portalsubmission",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="complaints.document",
            ),
        ),
        migrations.AddField(
            model_name="portalsubmission",
            name="office",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.office"),
        ),
        migrations.AddField(
            model_name="referral",
            name="complaint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referrals",
                to="complaints.complaint",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="notice_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="complaints.document",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="office",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.office"),
        ),
        migrations.AddField(
            model_name="referral",
            name="to_department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.department"
            ),
        ),
        migrations.AddField(
            model_name="inquiryreport",
            name="referral",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="report",
                to="complaints.referral",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="office",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.office"),
        ),
        migrations.AddField(
            model_name="complaint",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="complaints", to="complaints.tag"
            ),
        ),
        migrations.AddIndex(
            model_name="complainant",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="complainant_name_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("extracted_text", config="simple"),
                name="doc_text_search_gin",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("complaint", "sha256"), name="uniq_document_complaint_sha"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["complaint", "occurred_at"], name="event_complaint_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="portalsubmission",
            constraint=models.UniqueConstraint(
                fields=("complaint", "attempt_no"), name="uniq_submission_attempt"
            ),
        ),
        migrations.AddConstraint(
            model_name="portalsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("outcome", "pending")),
                fields=("complaint",),
                name="one_pending_submission_per_complaint",
            ),
        ),
        migrations.AddConstraint(
            model_name="referral",
            constraint=models.UniqueConstraint(
                fields=("complaint", "round_no"), name="uniq_referral_round"
            ),
        ),
        migrations.AddConstraint(
            model_name="referral",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed_on__isnull", True)),
                fields=("complaint",),
                name="one_open_referral_per_complaint",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("office", "name"), name="uniq_tag_office_name"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["office", "current_state"], name="cmp_office_state_idx"),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["office", "current_department"], name="cmp_office_dept_idx"),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["office", "received_on"], name="cmp_office_received_idx"),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["village"], name="cmp_village_idx"),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["source_platform"], name="cmp_platform_idx"),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "ref_no", "external_ref", "subject", "description", config="simple"
                ),
                name="cmp_search_vector_gin",
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["subject"], name="cmp_subject_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddConstraint(
            model_name="complaint",
            constraint=models.UniqueConstraint(
                fields=("office", "ref_no"), name="uniq_complaint_office_ref"
            ),
        ),
    ]
