# Generated by Django 5.2.17 on 2026-10-03 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("complaints", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiryreport",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="complaints.document",
            ),
        ),
        migrations.AlterField(
            model_name="portalsubmission",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="complaints.document",
            ),
        ),
    ]
